openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /api/users/create:
    post:
      description: "Create a new user"
      responses:
        "201":
          description: "User created"
          $ref: "#/components/schemas/FullUser"
          content:
            application/json:
              schema:
                type: FullUser

components:
  schemas:
    FullUser:
      description: "All user details"
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
